In [12]:
text="I had a good sleep yesterday."

In [13]:
import re

words=re.findall(r"\w+|[^\w\s]+",text)

print(words)

['I', 'had', 'a', 'good', 'sleep', 'yesterday', '.']


In [16]:
vocab = list(set(words))

print(vocab)

['good', 'a', 'sleep', '.', 'yesterday', 'I', 'had']


In [17]:
word_to_id = {word : idx for idx,word in enumerate(vocab) }
id_to_word = {id:word for word,id in word_to_id.items()}

In [18]:
word_to_id

{'good': 0, 'a': 1, 'sleep': 2, '.': 3, 'yesterday': 4, 'I': 5, 'had': 6}

In [45]:
import numpy as np

vocab_size = len(word_to_id)
cooccur_mat = np.zeros((vocab_size, vocab_size))
print(cooccur_mat.shape)

(7, 7)


In [21]:
corpus = [word_to_id[word] for word in words]

In [22]:
print(corpus)

[5, 6, 1, 0, 2, 4, 3]


In [46]:
window_size=2
for word_pos,word_id in enumerate(corpus):
    for idx in range(1,window_size+1):
        left_context_idx = word_pos - idx
        right_context_idx = word_pos + idx
        
        if left_context_idx > 0:
            left_word_id = corpus[left_context_idx]
            cooccur_mat[word_id,left_word_id] += 1
        if right_context_idx < len(corpus):
            right_word_id = corpus[right_context_idx]        
            cooccur_mat[word_id, right_word_id] += 1

In [47]:
print(cooccur_mat)

[[0. 1. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0. 1.]
 [1. 1. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0. 0.]]


In [49]:

print("vector representation of I", cooccur_mat[word_to_id["I"]])
print("word id of I",word_to_id["I"])
print("word id of had", word_to_id["had"])
print("word id of a",word_to_id["a"])

vector representation of I [0. 1. 0. 0. 0. 0. 1.]
word id of I 5
word id of had 6
word id of a 1
