In [1]:
import numpy as np
from utils import create_cooccurrence_matrix,tokenize,build_vocabulary,get_word_to_id_from_vocab,get_id_to_word,build_corpus

In [2]:
text = "I had a good sleep yesterday"

In [3]:
words = tokenize(text)
vocab = build_vocabulary(words)
word_to_id = get_word_to_id_from_vocab(vocab)
id_to_word = get_id_to_word(word_to_id)


In [4]:
corpus = build_corpus(words,word_to_id)

In [5]:
C = create_cooccurrence_matrix(corpus,window_size=1,vocab_size=len(vocab))

In [6]:
print(C)

[[0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]]


In [7]:
M = np.zeros_like(C, dtype=np.float32)
N = np.sum(C)
S = np.sum(C, axis=0)
eps=1e-8
for row_idx in range(C.shape[0]):
    for col_idx in range(C.shape[1]):
        pmi = np.log2(C[row_idx,col_idx]*N/(S[row_idx]*S[col_idx])+eps)
        M[row_idx, col_idx] = max(0,pmi)

In [8]:
print(S)
print(np.sum(C,axis=1))

[2. 1. 2. 2. 1. 2.]
[2. 1. 2. 2. 1. 2.]


In [9]:
print(M)

[[0.        0.        0.        1.3219281 0.        1.3219281]
 [0.        0.        0.        2.321928  0.        0.       ]
 [0.        0.        0.        0.        2.321928  1.3219281]
 [1.3219281 2.321928  0.        0.        0.        0.       ]
 [0.        0.        2.321928  0.        0.        0.       ]
 [1.3219281 0.        1.3219281 0.        0.        0.       ]]
